### ISSUE TITLE
add support for "forgot password" link and email process

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-api-server#128]
We need to add a "forgot password" link support to the webapp.  This actually exists in the hosted (jambonz.xyz) system but not in the main one.  So there is some code there to look at but we need some changes. Most of the changes need to be made here, in the api-server.  

You will find some code in there that works with mailgun (e.g. requires mailgun api key).  However, we cant force people to use mailgun they should be able to use any email provider.  I think the best thing is that there is a new env var that gives an http endpoint we can post to that the customer will implement to send out mail.  We'll probably need optional envs for http basic auth user and password as well.  Then they can plug in their own email provider, and we can then add a "forgot password" link to the webapp that will generate the email via the http post.

**Comment by xquanluu** [comment]
start working on this.

**Comment by xquanluu** [comment]
Closed as PR is merged
