### ISSUE TITLE
Missing properties in Swagger yaml

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-api-server#13]
Missing following fields on Update Call Body:
-child_call_hook

Missing following fields on Create Call Body:
-headers

Missing following fields on Target:
-vmail
-tenant
-overrideTo

Also missing the queues endpoint for querying queue counts

**Comment by davehorton** [comment]
@Egle can you check the above and update the swagger.yml doc if appropriate (ie if those fields are indeed missing)?
