### ISSUE TITLE
feature: least cost routing

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-api-server#151]
The branch feature/lcr has been opened to work on this feature.  The api needs to support the needs of the webapp in creating LCR tables as described [here](https://github.com/jambonz/jambonz-webapp/issues/236).

The schema changes below have already been checked in on this branch:

![schema](https://user-images.githubusercontent.com/1884973/231856305-05813eda-c99b-4e24-aa31-9994c212147c.jpg)

- **lcr** represents an LCR table.  It has a name and a default route.  An LCR can be associated with either a single SP or account.
- **lcr_routes** represents digit match patterns in an LCR table.  They have an explicit ordering (priority) and are evaluated in order from low to high priority value until a match is found.
- **lcr_carrier_set_entry** represents the carrier route to take when a digit pattern is matched.  In the first version of this feature this will always resolve to a single carrier, but the schema is meant to support two other scenarios: route to a list of carriers in crankback fashion (try carrier 1, if fails try carrier 2), or distribution (send 80% of traffic to carrier 1, 20% to carrier 2).

LCR is an optional feature.  A service provider may have an LCR table or not, ditto an account.  An LCR table however is associated with only one service provider or account entity.

**Comment by xquanluu** [comment]
start working on this

**Comment by xquanluu** [comment]
PR merged,

Closing this issue
