### ISSUE TITLE
record call feature

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-api-server#167]
This work is related to the associated [jambonz-webapp feature request](https://github.com/jambonz/jambonz-webapp/issues/251).

The changes to the api-server will be two-fold:
1. The database and REST api will need to change to support the new properties being provisioned from the webapp
2. The process will need to expose a new websocket server endpoint, because we are going to use the [listen](https://www.jambonz.org/docs/webhooks/listen/) verb, nested in a [config](https://www.jambonz.org/docs/webhooks/config/), to stream the call audio to wss endpoint that the api-server exposes.

The first point is fairly self-explanatory.

the second deserves some more commentary.  The api-server is an express app, and now it will be modified to mount a websocket server endpoint.  The endpoint will be reached at the path `/record`, e.g. "https://jambonz.xyz/api/record".  Once the websocket connection is established there will be a text frame sent with the call_sid and other metadata (as is done over all listen sockets).  The api-server shall receive this frame and create a file with the given call_sid as the filename (with a filetype of .raw) and metadata that includes the account_sid and the sample rate.  As the binary frames then come in with raw audio they should be uploaded to the file in the specified bucket.

**Comment by xquanluu** [comment]
Hi @davehorton 
when uploading to buket, instead of common the filename like: <call-sid>_<account-sid>_<sample-rate>.raw

We can seprated them by account sid application sub folder:

/<account-sid>/<application-sid>/<call-sid>_<sample-rate>.raw

**Comment by davehorton** [comment]
I think separating them by folder would be a good idea however I think I would prefer something like
```
/<year>/<month>/<day>/<call-sid>.raw
```
with sample rate and account_sid as metadata attached to the file, not in the file name
