### ISSUE TITLE
application update api call throws a 500 "Unknown column" error

### ISSUE THREAD

**Issue by hpasapp** [jambonz/jambonz-api-server#171]
Trying:

```
curl --location -g --request PUT 'http://[base url]/api/v1/Applications/[app sid]' \
--header 'Authorization: Bearer [api key]' \
--data '{
    "call_hook": {
        "url": "https:foo/bar"
    }
}'
```

What I expect to happen:
- set the call hook for my application to https://foo/bar

What actually happens:

```
{"msg":"Unknown column '{\n    \"call_hook\": {\n        \"url\": \"https:foo/bar\"\n    }\n}' in 'field list'"}
```

**Comment by hpasapp** [comment]
git commits:

jambonz-api-server:
```
admin@ip-10-0-74-237:~/apps/jambonz-api-server$ git log -n 1
commit 34895daf4fe6effa7e947c3a96ffe24b804d30c2 (HEAD, tag: v0.8.3, origin/main, origin/HEAD)
Author: Hoan Luu Huu <110280845+xquanluu@users.noreply.github.com>
Date:   Fri May 12 07:27:19 2023 +0700

    fix admin setting issue (#168)
```

jambonz-feature-server:
```
commit fb1801ce11fe038cd1b25991013485d893b9da0f (HEAD, tag: v0.8.3, origin/main, origin/HEAD)
Author: Dave Horton <daveh@beachdognet.com>
Date:   Thu May 11 10:51:08 2023 -0400

    0.8.3
```

**Comment by davehorton** [comment]
Please include the following header in your curl command
```
Content-Type: application/json
```
This should fix it.

**Comment by hpasapp** [comment]
Thank you :)

**Comment by hpasapp** [comment]
Awesome! Yes :)

On Fri, May 19, 2023 at 5:34 PM Dave Horton ***@***.***>
wrote:

> Please include the following header in your curl command
>
> Content-Type: application/json
>
> This should fix it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jambonz_jambonz-2Dapi-2Dserver_issues_171-23issuecomment-2D1555277673&d=DwMCaQ&c=xKASDZkv8eA7-1KZwNrOLw&r=ICi59hpZNRHTBZh2aK6sVg&m=wv710wYAXNiNJOLFoQa2vTDZ39wHKS5HYOwyrMC7Iym8IHOVk4Lqn-TB_iU_mdYa&s=2Y7152hpiIyrR7rG2H0GtgOtBV-og9IT861Tn7YQr8E&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEZ5OBEE5ABAGWPIFED5SM3XG7RM7ANCNFSM6AAAAAAYIHQYQY&d=DwMCaQ&c=xKASDZkv8eA7-1KZwNrOLw&r=ICi59hpZNRHTBZh2aK6sVg&m=wv710wYAXNiNJOLFoQa2vTDZ39wHKS5HYOwyrMC7Iym8IHOVk4Lqn-TB_iU_mdYa&s=bqbKYPXwBnPtJnMNq58nuoO65ZrTAxjO1YCzjzQdcZ4&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
*HUGH PERKINS*
Research Engineer


<https://www.asapp.com/>
One World Trade Center
80th Floor
New York, NY 10007
