### ISSUE TITLE
in EC2 if multiple feature servers apps are running api-server sends to only one

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-api-server#190]
In an AWS clustering environment, we made changes so that pm2 can start multiple instances of jambonz-feature-server.  Each listens on an HTTP port, by default 3000, but if that port is claimed they will back off to the next one.  So if we started 4 instances in pm2 they would be listening on ports 3000-3003.

However, when sending a REST api command like createCall to a feature server, the api-server always assumes the FS is listening on 3000, as we see here:

https://github.com/jambonz/jambonz-api-server/blob/a0797a3a4c4d2ed2dfe76ea93346d834e7eee533/lib/routes/api/accounts.js#L46

Thus all REST api commands would go to only one of the FS app instances.  We should make it so that api-server is aware of the http listen ports of the various FS instances and round robins

**Comment by xquanluu** [comment]
start working on this.

**Comment by xquanluu** [comment]
all PRs merged, closing this
