### ISSUE TITLE
RangeError: start offset of Int16Array should be a multiple of 2

### ISSUE THREAD

**Issue by juansalvatella** [jambonz/jambonz-api-server#200]
While recording a call with MP3 we get the following error:

> RangeError: start offset of Int16Array should be a multiple of 2
>     at new Int16Array (<anonymous>)
>     at PCMToMP3Encoder._transform (/opt/app/lib/record/encoder.js:18:21)
>     at Transform._write (node:internal/streams/transform:175:8)
>     at writeOrBuffer (node:internal/streams/writable:392:12)
>     at _write (node:internal/streams/writable:333:10)
>     at Writable.write (node:internal/streams/writable:337:10)
>     at Duplex.ondata (node:internal/streams/readable:766:22)
>     at Duplex.emit (node:events:513:28)
>     at addChunk (node:internal/streams/readable:324:12)
>     at readableAddChunk (node:internal/streams/readable:297:9)

We are getting this error almost every time we record a call but we have been able to record some without this issue. Any hints on what info would be necessary to properly troubleshoot this?

**Comment by xquanluu** [comment]
Hi @juansalvatella 
Thanks a lot, Can I have jambonz application json?

I need that to reproduce the issue locally.

**Comment by xquanluu** [comment]
Hi @juansalvatella 
I think that the chunk.length is odd that make chunk.length/2 is in bad result.

Can you please help me to add this

// Convert chunk buffer into Int16Array for lamejs
    console.log(chunk.length, chunk.length/2);
    const samples = new Int16Array(chunk.buffer, chunk.byteOffset, chunk.length / 2);
    
    And check what is the output, can you copy that output to this issue as well?

**Comment by juansalvatella** [comment]
Sure! Let me add that and I'll get back to you. I'm preparing also a json app to reproduce the issue.

**Comment by juansalvatella** [comment]
I've been able to create this sample app that reproduces this issue: `https://storage.googleapis.com/bookline-rec/sample.json`

1. Press any digit
2. Say anything

The call will be terminated and you will be able to see the following error on the logs:

```
/opt/app/lib/record/encoder.js:19
    const samples = new Int16Array(chunk.buffer, chunk.byteOffset, chunk.length / 2);
                    ^

RangeError: start offset of Int16Array should be a multiple of 2
    at new Int16Array (<anonymous>)
    at PCMToMP3Encoder._transform (/opt/app/lib/record/encoder.js:19:21)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Duplex.ondata (node:internal/streams/readable:766:22)
    at Duplex.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)

Node.js v18.15.0
```

I added the console.log and this is how it progresses throughout the call:

`
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1920 960
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
1280 640
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
640 320
45 22.5
640 320
`

**Comment by xquanluu** [comment]
Thanks a lot @juansalvatella 

You can see this pair: 45 22.5

This is really bad, we are expecting that streaming audio to api-server is sterio and there should always be 2 sites audio, but here one package is 45 (odd).

I will try to reproduce this issue and fix it asap.

**Comment by xquanluu** [comment]
Hi @juansalvatella 

Can you help to check if the sample app is returning json app, currently it's returning 400 Bad request

`30|jambonz | {"level":20,"time":1689552070459,"pid":2032832,"hostname":"ip-10-0-214-82","callId":"e0c235c2-9ed7-123c-f0ae-161343ac42f3","callSid":"1018626b-287d-462c-81c4-f839a93edbc7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"xhoaluu","calledNumber":"123","traceId":"707e8c07750e62b1422d7a8e141a7446","url":"https://storage.googleapis.com/bookline-rec/sample.json","absUrl":"https://storage.googleapis.com/bookline-rec/sample.json","hdrs":{"Jambonz-Signature":"t=1689552070,v1=e546729e45be25913ef4c4e38e3aa3e57b02750678af17602c393e6f379109e1","b3":"707e8c07750e62b1422d7a8e141a7446-2e7293845de399f5-1","Content-Type":"application/json"},"msg":"send webhook"}
30|jambonz | {"level":30,"time":1689552071103,"pid":2032832,"hostname":"ip-10-0-214-82","callId":"e0c235c2-9ed7-123c-f0ae-161343ac42f3","callSid":"1018626b-287d-462c-81c4-f839a93edbc7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"xhoaluu","calledNumber":"123","traceId":"707e8c07750e62b1422d7a8e141a7446","baseUrl":"https://storage.googleapis.com","url":"https://storage.googleapis.com/bookline-rec/sample.json","msg":"web callback returned unexpected status code 400"}`

**Comment by xquanluu** [comment]
This is already fixed
