### ISSUE TITLE
REST PhoneNumbers endpoint

### ISSUE THREAD

**Issue by rjp44** [jambonz/jambonz-api-server#215]
There doesn’t currently seem to be a documented REST endpoint to list and modify phone numbers  at https://api.jambonz.org/. It used to be possible to call the undocumented /api/v1/PhoneNumbers with an account scoped API key. I understand there was possibly a security problem with this. At some point this has become /api/v1/ServiceProviders/:id/PhoneNumbers, but there is no /api/v1/Accounts/:id/PhoneNumbers. Service provider scoped works fine for me with an admin scoped API key on my private instances, but gives a 403 on the new jambonz.cloud instances as a user with an account scoped API key. I think this means that there is no way to access any PhoneNumbers API on public instances at present?

**Comment by davehorton** [comment]
@xquanluu can you investigate?  We need to make sure an account user does not have create/edit/delete access on a phone number associated with an SP trunk, but should have the same on an account trunk for their account
