### ISSUE TITLE
Service Crashes and Restarts on `isValidWsKey` with Call Recording Feature Enabled

### ISSUE THREAD

**Issue by guilherme-rauen** [jambonz/jambonz-api-server#222]
When setting the JAMBONZ_RECORD_WS_PASSWORD to a random 128-chars alphanumeric code, api-server started to throw this error and restart:

TypeError: Cannot read properties of null (reading '1')
     at isValidWsKey (/opt/app/app.js:195:13)
     at Server.<anonymous> (/opt/app/app.js:211:8)
     at Server.emit (node:events:513:28)
     at Server.emit (node:domain:489:12)
     at onParserExecuteCommon (node:_http_server:903:14)
     at onParserExecute (node:_http_server:797:3)
{"level":50,"time":1692699022976,"pid":1,"hostname":"api-server-6dc569dc54-m84zk","msg":"Uncaught exception error caught. Error was: Cannot read properties of null (reading '1')","v":1}

Looking a bit more into it, the issue is happening in this function:

const isValidWsKey = (hdr) => {
  const username = process.env.JAMBONZ_RECORD_WS_USERNAME;
  const password = process.env.JAMBONZ_RECORD_WS_PASSWORD;
  const token = Buffer.from(`${username}:${password}`).toString('base64');
  const arr = /^Basic (.*)$/.exec(hdr);
  return arr[1] === token;
};

At first, I thought the issues was that `arr` was being null because the TypeError was clear pointing to the attempt of accessing index 1 of null. But by simply reducing the password to a 32-chars code, it started to work. So, my guess is that we have some sort of limitation on size here. And the error is not exactly where it appears to be looking into the logs.

**Comment by xquanluu** [comment]
Hi @guilherme-rauen 
I cannot reproduce the issue,

can you please let me know if you have provisioned these credential on feature server environment variables

This issue will happen if, feature server who is sending audio data to api-server for recording and you just provisioned password on api-server only.

**Comment by guilherme-rauen** [comment]
Hi @xquanluu 

Yes, the credentials were provisioned on feature-server and api-server. The setup is a kubernetes cluster and the password is a secret that is then passed to the environment variables of both services. The secret was 128-char alphanumeric code, once I changed to a smaller code (32-char) it did not crash anymore.

**Comment by xquanluu** [comment]
Hi I tested with local unit test for the code

const token = Buffer.from(${username}:${password}).toString('base64');
const arr = /^Basic (.*)$/.exec(hdr);

It's working.

I think with 128 chars length username and password, it create a really long base64 string and cause the string is trimmed when it's added in http headers for ws.

I think username and password 32 chars long string is already good enough.

I don't think we have to support for really long username and password. what do you think? @guilherme-rauen

**Comment by guilherme-rauen** [comment]
Hi @xquanluu,

Yes, I think it is not needed to support such a long combination for this internal communication (api-server <> feature-server), but it is good to know that there is a limitation in the length of these creds, especially in these cases that you create random secrets value in kubernetes just passing the length that your secret should have. I don't know if needs an entry in the documentation, but at least now, we know one more thing to look if someone reports something like this.

Thanks for taking a look, I think we reached the same conclusion.
