### ISSUE TITLE
replace use of .pipe() with .pipeline()

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-api-server#316]
Replace this implementation

https://github.com/jambonz/jambonz-api-server/blob/2436bea6eaa593eba25530e77c2a8d60c3dfaae3/lib/record/upload.js#L71

with pipeline, as described in 

https://www.youtube.com/watch?v=edB964-YYpE&list=PL_x4nRdxj60K2j9l_SflmqmaTA2XVBuqc

starting 28:16 into the video, describing the problems of using .pipe

**Comment by xquanluu** [comment]
the PR is merged, closing this issue
