### ISSUE TITLE
Create Call methods (v2, v3) don't seem to work 

### ISSUE THREAD

**Issue by Megamuch** [jambonz/jambonz-api-server#79]
When trying to create a call via the API the documentation allows different methods for creating calls. In Version 2 the webhook is explicitly provided in the payload in place of an application_sid. All attempts to use this seem to fail. 

The only method that works is the method that sends in the application_sid, ie V1.

`{
    "application_sid" :"33c37050-d44b-495b-befc-XXXXXXXXX",
    "from": "3110xxxxxxx",
    "to": {
        "type": "phone",
        "number": "316xxxxx"
    }
}`

**Comment by davehorton** [comment]
in version 2 you need to supply your speech choices, since we can't get them from an application, iei

```
{
      call_hook: "https://public-apps.jambonz.us/hello-world",
      call_status_hook: "https://public-apps.jambonz.us/call-status",
      from: "15083778299",
      to: {
        type: "phone",
        number: "15089084809"
      },
      speech_synthesis_vendor: "google",
      speech_synthesis_language: "en-US",
      speech_synthesis_voice: "en-US-Standard-C",
      speech_recognizer_vendor: "google",
      speech_recognizer_language: "en-US"
    }
```
