### ISSUE TITLE
Problem in docker image

### ISSUE THREAD

**Issue by andreabat** [jambonz/jambonz-api-server#94]
Hi,
I have been trying to use the docker image ( using jambonz-infrastructure docker-compose) for the api-server , but login call fails when verifying hash in the argon2-ffi library.

{"level":50, "time": "2023-01-18T15:25:22.569Z","pid":1,"hostname":"e624e6d12fce","msg":"Database error","stack":"Error: Decoding failed\n    at resultHandler (/opt/app/node_modules/argon2-ffi/lib/index.js:118:25)\n    at Object.<anonymous> (/opt/app/node_modules/ffi-napi/lib/_foreign_function.js:115:9)","type":"Error","v":1}

I have tried different versions of the image, but to no avail, same error.

Node version in container image is v18.12.1 

Using standard default admin user and password

**Comment by davehorton** [comment]
If you are running against data provisioned some time ago, e.g on an older release, then a different hashing method was used and that could be (likely) why.  Secondly, the docker-compose in the jambonz-infrastructure repo has not received much attention and is very out of date.  Unfortunately with limited resources we've not been able to tend to it, instead focusing our energies on Kubernetes (via helm chart) and EC2 (via cloudformation).  I'd highly recommend either of those deployments

**Comment by andreabat** [comment]
Ok, will try ec2, although it would have been nicer to have on premise in order to test integration with my existing freeswitch infra and exposing it to aws is a bit of a hassle. Kubernetes is a bit of an overkill for local development.

Just for your information, I don't think it is related to the provisioned data . the library fails in REPL mode with a basic .verify call.
Since argon2 code is outdated ( in node standards) my guess is that node 18 ( which has quite a few breaking changes ) might be incompatible.

> A.argon2i.verify("aaa","admin")
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 262,
  [Symbol(trigger_async_id_symbol)]: 5
}
> /opt/app/node_modules/argon2-ffi/lib/index.js:118
          return reject(new Error(argon2ErrorMessage(res)));
                        ^

Error: Decoding failed
    at resultHandler (/opt/app/node_modules/argon2-ffi/lib/index.js:118:25)
    at Object.<anonymous> (/opt/app/node_modules/ffi-napi/lib/_foreign_function.js:115:9)
    at Ob
